name: drMD_wnk_umbrella
channels:
  - conda-forge
  - defaults

dependencies:
  # ============================================================================
  # Core OpenMM Stack
  # ============================================================================
  - python=3.8
  - openmm=7.7.0  # Latest stable (NOT 7.4.1 - outdated on Yoltla)
  - cudatoolkit=11.2  # Match Yoltla's CUDA 11.2 module
  
  # ============================================================================
  # Enhanced Sampling Extensions
  # ============================================================================
  - openmm-plumed  # For metadynamics, steered MD, collective variables
  - openmmtools  # Additional integrators, MCMC, alchemical tools
  
  # ============================================================================
  # Free Energy Analysis Tools (CRITICAL)
  # ============================================================================
  - pymbar>=4.0.0  # ⚠️ MUST be >=4.0 for timeseries.subsampleCorrelatedData()
  - mdtraj  # Trajectory analysis, RMSD, distances
  - pdbfixer  # PDB cleanup, missing residues, protonation
  
  # ============================================================================
  # Scientific Python Ecosystem
  # ============================================================================
  - numpy>=1.20.0
  - scipy>=1.7.0
  - pandas>=1.3.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  
  # ============================================================================
  # Workflow & Productivity
  # ============================================================================
  - pyyaml
  - tqdm  # Progress bars
  - jupyter  # Interactive analysis notebooks
  - ipython
  
  # ============================================================================
  # Visualization
  # ============================================================================
  - nglview  # Interactive 3D molecular visualization in Jupyter
  - py3Dmol  # Alternative molecular viewer
  
  # ============================================================================
  # Testing & Development
  # ============================================================================
  - pytest
  - pytest-cov
  - black  # Code formatting
  
  # ============================================================================
  # Additional Tools (via pip)
  # ============================================================================
  - pip:
    - propka  # pKa prediction for protonation states (not in conda)
    - h5py  # HDF5 file support for large trajectory storage
    - networkx  # For protein network analysis

# ============================================================================
# Post-Installation Verification Commands
# ============================================================================
# After creating this environment, run:
#
#   conda activate drMD_wnk_umbrella
#   python -c "import openmm; print(f'OpenMM: {openmm.__version__}')"
#   python -c "import pymbar; print(f'pymbar: {pymbar.__version__}')"
#   python -c "from openmmplumed import PlumedForce; print('PLUMED: OK')"
#   python -c "from openmm import Platform; print([Platform.getPlatform(i).getName() for i in range(Platform.getNumPlatforms())])"
#
# Expected output:
#   OpenMM: 7.7.0
#   pymbar: 4.x.x
#   PLUMED: OK
#   ['Reference', 'CPU', 'CUDA', 'OpenCL']
#
# If CUDA not available, check:
#   module load cuda/11.2
#   export OPENMM_CUDA_COMPILER=/usr/local/cuda-11.2/bin/nvcc
# ============================================================================
